spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8082
  servlet:
    context-path: /booklibrary
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    enabled: true